### ISSUE TITLE
Multiple UI windows open cause problems.

### ISSUE THREAD

**Issue by Andreya-Autumn** [eventual-recluse/LiveCut#4]
Load two instances and open both UIs. If you toggle between the cut procedures in one, you'll see it change in the other also.

**Comment by eventual-recluse** [comment]
So it does, and all the combo boxes do that! Looks like it's due to the pointers the combo boxes use. The best thing is probably to look into reprogramming the GUI with a more suitable library, which I don't mind doing, seen as Dear ImGui wasn't designed with multiple instances of audio plugins in mind.

**Comment by Andreya-Autumn** [comment]
Yeah that's also what my friend said. He and a few others tried to make Dear ImGui work for plugins a few years back, but never cracked this. Again, welcome over to the SST Discord to discuss this further if you'd like. :)

**Comment by eventual-recluse** [comment]
It should be working now... hopefully.

Thanks for the link! I will be joining.

**Comment by Andreya-Autumn** [comment]
Hey, looks like it is! Nice. :)
